# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       xorg-x11-proto-xproxymanagementprotocol
Summary:    X.Org X11 Protocol xproxymanagementprotocol
Version:    1.0.3
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/xproxymanagementprotocol-%{version}.tar.bz2
Source100:  xorg-x11-proto-xproxymanagementprotocol.yaml
Provides:   xproxymanagementprotocol


%description
- %{summary}.




%prep
%setup -q -n xproxymanagementprotocol-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/xproxymngproto.pc
%{_includedir}/X11/PM/PM.h
%{_includedir}/X11/PM/PMproto.h
%doc %{_datadir}/doc/xproxymanagementprotocol/PM_spec
# << files


